# Generated by Django 3.1.5 on 2021-01-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effort', models.PositiveIntegerField()),
                ('base_stat', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_poke_api', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_poke_api', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('height', models.DecimalField(decimal_places=3, max_digits=6)),
                ('id_poke_api', models.PositiveIntegerField(unique=True)),
                ('base_stats', models.ManyToManyField(to='pokemon.BaseStats')),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.evolutionchain')),
            ],
        ),
        migrations.AddField(
            model_name='evolutionchain',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemonspecies'),
        ),
        migrations.AddField(
            model_name='evolutionchain',
            name='evolves_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='pokemon.pokemonspecies'),
        ),
    ]
